[versions]
# https://github.com/JetBrains/kotlin
kotlin = "2.2.20"
coroutines = "1.10.2"
shadowroutines = "0.0.1-SNAPSHOT"

# https://github.com/Kotlin/binary-compatibility-validator
kotlin-binaryCompatibilityValidator = "0.16.3"

# https://github.com/junit-team/junit4
junit = "4.13.2"

# https://github.com/gmazzo/gradle-buildconfig-plugin
buildconfig = "5.6.5"

# https://github.com/JetBrains/compose-multiplatform
compose = "1.10.0"
compose-plugin = "1.8.2"

[libraries]
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinhax-shadowroutines-core = { group = "com.woutwerkman.kotlinhax", name = "kotlinhax-shadowroutines-core", version.ref = "shadowroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-script-runtime = { group = "org.jetbrains.kotlin", name = "kotlin-script-runtime", version.ref = "kotlin" }
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }
kotlin-test-framework = { group = "org.jetbrains.kotlin", name = "kotlin-compiler-internal-test-framework", version.ref = "kotlin" }
kotlin-annotations-jvm = { group = "org.jetbrains.kotlin", name = "kotlin-annotations-jvm", version.ref = "kotlin" }
kotlin-compiler = { group = "org.jetbrains.kotlin", name = "kotlin-compiler", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-gradle-plugin-api  = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin-api", version.ref = "kotlin" }

junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlin-binaryCompatibilityValidator"}
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig"}
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-compose-gradle = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }

gradle-java-test-fixtures = { id = "java-test-fixtures" }
gradle-idea = { id = "idea" }
gradle-plugin = { id = "java-gradle-plugin" }
